SERVER: Fixed doors only targeting first target
nzp-team/quakec pull request #56
Opened 2023-05-07 01:57 UTC by notrickzdumbo

Fixed doors only targeting first target by removing the lines setting all the targets to the first one.

**Platforms tested**
PC - Confirmed by me and BCDeshiG
PSP - Confirmed by BCDeshiG
3DS - Confirmed by me

2023-05-07 03:00 UTC, Naievil commented
What bug does this fix?

This was needed in order to activate all zombie spawns once a door is triggered.

2023-05-07 04:45 UTC, notrickzdumbo commented
> What bug does this fix?
> 
> This was needed in order to activate all zombie spawns once a door is triggered.

An issue wasn't actually created for this. But this allows for doors to have multiple targets which is needed for two way doors. Maybe it wouldn't really be much of a bug but rather a suggestion, other than the fact that this fixes official maps and looking at the .map file of the new nacht der untoten it's even expected to behave this way on some parts like the staircases.

And from my testing all the zombie spawns on a given target still activate with these changes since the function SUB_UseTargets seems to loop over all entities with the given target name being checked.

2023-05-07 17:34 UTC, MotoLegacy requested changes
Piggybacking off of @Naievil, this was in relation to multiple `ai_zombie`'s that have the same targetname, I believe. Definitely a hack, but it would set all of the targets to the same string so that it would find "all" (or really, 8) potential spawns and mark them as active.

This fix is definitely useful, however it should be verified this doesn't break that original functionality. If it does, please make an additional commit for this `SUB_UseTargets` change to make sure it's iterating through every entity with that targetname instead of just one, for compatibility.

2023-05-20 13:52 UTC, MotoLegacy commented
As its been 2 weeks now, please convert this PR to a draft until a fix has been made. Thanks!

2023-05-21 13:34 UTC, BCDeshiG commented
Cooked up a quick test map to check if all the spawns are being triggered.
All of the zombies have the same target name here so they should all fire when buying the 'door'.
[triggerTEST.zip](https://github.com/nzp-team/quakec/files/11524646/triggerTEST.zip)

2023-05-21 14:40 UTC, BCDeshiG commented
So far, testing on PC all 18 spawns get triggered by the one door so no regressions have occurred there at least.

2023-05-21 15:22 UTC, BCDeshiG commented
Can confirm no regressions on PSP either.

2023-05-21 16:09 UTC, MotoLegacy commented
LGTM then

2023-05-21 16:10 UTC, MotoLegacy approved these changes

2023-05-21 16:31 UTC, notrickzdumbo commented
> Cooked up a quick test map to check if all the spawns are being triggered. All of the zombies have the same target name here so they should all fire when buying the 'door'. [triggerTEST.zip](https://github.com/nzp-team/quakec/files/11524646/triggerTEST.zip)

No issues with this map on 3DS either. Apologies for the downtime.

2023-05-24 19:13 UTC, Naievil approved these changes
Thanks for confirmation that there is no regression!

2023-05-24 20:11 UTC, merged