CLIENT: Don't draw hud if the game is over
nzp-team/quakec pull request #98
Opened 2024-12-19 01:45 UTC by Peter0x44

Fixes https://github.com/nzp-team/nzportable/issues/1042

2024-12-26 21:26 UTC, MotoLegacy requested changes

2024-12-26 21:26 UTC, MotoLegacy commented on source/server/weapons/weapon_core.qc
> +	if (self.switch_delay > time || self.dive || self.isBuying || game_over)
We should probably make sure we just take away the weapon completely when game over starts that way we aren't potentially neglecting other issues (like whether you can reload for example).

2024-12-31 13:46 UTC, Peter0x44 commented on source/server/weapons/weapon_core.qc
> +	if (self.switch_delay > time || self.dive || self.isBuying || game_over)
Done.

2024-12-31 16:20 UTC, MotoLegacy commented
Looks good, please settle the merge conflict and then I can accept.

2025-01-02 00:51 UTC, merged